export default [
  {
    rules: {
      "array-callback-return": ["error", { checkForEach: true }],
      "for-direction": "error",
      "no-async-promise-executor": "error",
      "no-await-in-loop": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": "error",
      "no-const-assign": "error",
      "no-constant-binary-expression": "error",
      "no-constant-condition": "error",
      "no-control-regex": "error",
      "no-dupe-args": "error",
      "no-dupe-else-if": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-duplicate-imports": "error",
      "no-inner-declarations": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-obj-calls": "error",
      "no-promise-executor-return": "error",
      "no-prototype-builtins": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-sparse-arrays": "error",
      "no-undef": "error",
      "no-unreachable": "error",
      "no-unreachable-loop": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-vars": "error",
      "no-use-before-define": "error",
      "no-useless-assignment": "error",
      "require-atomic-updates": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      // "arrow-body-style": ["error", "as-needed"], https://github.com/prettier/eslint-plugin-prettier?tab=readme-ov-file#arrow-body-style-and-prefer-arrow-callback-issue
      "block-scoped-var": "error",
      camelcase: "error",
      complexity: ["error", 3],
      "consistent-return": "error",
      curly: "error",
      "default-case": "error",
      "default-case-last": "error",
      "default-param-last": "error",
      "dot-notation": "error",
      eqeqeq: "error",
      "func-style": ["error", "declaration", { allowArrowFunctions: true }],
      "guard-for-in": "error",
      "id-denylist": ["error", "data", "err", "e", "cb", "callback"],
      "id-length": ["error", { min: 4 }],
      "logical-assignment-operators": "error",
      "max-depth": ["error", 3],
      "max-nested-callbacks": ["error", 3],
      "no-alert": "error",
      "no-array-constructor": "error",
      "no-caller": "error",
      "no-console": "error",
      "no-delete-var": "error",
      "no-else-return": "error",
      "no-empty": "error",
      "no-empty-function": "error",
      "no-extend-native": "error",
      "no-extra-boolean-cast": "error",
      "no-implicit-coercion": "error",
      "no-implicit-globals": "error",
      "no-inline-comments": "error",
      "no-lonely-if": "error",
      "no-nested-ternary": "error",
      "no-throw-literal": "error",
      "no-undefined": "error",
      "no-unneeded-ternary": "error",
      "no-useless-catch": "error",
      "no-useless-return": "error",
      "no-var": "error",
      "object-shorthand": "error",
      // "prefer-arrow-callback": "error", https://github.com/prettier/eslint-plugin-prettier?tab=readme-ov-file#arrow-body-style-and-prefer-arrow-callback-issue
      "prefer-const": "error",
      "prefer-destructuring": "error",
      "prefer-object-spread": "error",
      "prefer-promise-reject-errors": "error",
      "prefer-rest-params": "error",
      "prefer-template": "error",
      "require-await": "error",
      "sort-imports": "error",
      "sort-keys": "error",
      "sort-vars": "error",
      strict: "error",
    },
  },
];
